version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools || dotnet tool update -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - echo "BUILDING LAMBDA PACKAGE"
      - cd SpendingControl.Api
      - dotnet restore
      - dotnet lambda package --configuration Release --framework net8.0 --output-package ../backend.zip

artifacts:
  files:
    - backend.zip