using System;

namespace SpendingControl.Domain.Entities
{
    public class SpendType
    {
        public int Id { get; set; } // PK
        public Guid UserId { get; set; } // owner
        public int Code { get; set; } // Autogenerated per user
        public string Name { get; set; } = null!;
        public bool IsActive { get; set; } = true;
    }
}