using System;

namespace SpendingControl.Domain.Entities
{
    public class SpendType
    {
        public int Id { get; set; } // PK
        public Guid UserId { get; set; } // owner
        public int Code { get; set; } // Autogenerated per user
        public string Name { get; set; } = null!;
        public bool IsActive { get; set; } = true;

        // Validate name and code
        public void Validate()
        {
            if (string.IsNullOrWhiteSpace(Name)) throw new ArgumentException("Name is required.", nameof(Name));
            if (Code <= 0) throw new ArgumentException("Code must be a positive integer. Use the generator to compute next code.", nameof(Code));
        }
    }
}